language: python
dist: xenial
services:
  - docker
virtualenv:
  system_site_packages: true
python:
  - '3.5'
  - '2.7'
addons:
  apt:
    packages:
    - docbook-utils
    - python-rpm
    - python3-rpm
    - rpm
install:
  - pip install flake8
script:
  - flake8
  - .travis/test.sh
  # the git clean is required so that we don't leak the virtualenv inside the container
  - git clean -dfx
  - docker run -v $(pwd):/app --workdir=/app --rm centos:7 bash .travis/test.sh
